"""Constants for Ukraine Alerts."""

from homeassistant.const import Platform

DOMAIN = "ukraine_alerts"
ATTRIBUTION = "Data provided by siren.pp.ua"
MANUFACTURER = "Ukraine Alerts"

ALERT_TYPE_UNKNOWN = "UNKNOWN"
ALERT_TYPE_AIR = "AIR"
ALERT_TYPE_ARTILLERY = "ARTILLERY"
ALERT_TYPE_URBAN_FIGHTS = "URBAN_FIGHTS"
ALERT_TYPE_CHEMICAL = "CHEMICAL"
ALERT_TYPE_NUCLEAR = "NUCLEAR"

ALERT_TYPES = {
    ALERT_TYPE_UNKNOWN,
    ALERT_TYPE_AIR,
    ALERT_TYPE_ARTILLERY,
    ALERT_TYPE_URBAN_FIGHTS,
    ALERT_TYPE_CHEMICAL,
    ALERT_TYPE_NUCLEAR,
}

THREAT_LEVEL_SAFE = "safe"
THREAT_LEVEL_YELLOW = "yellow"
THREAT_LEVEL_RED = "red"

THREAT_KIND_ROCKET = "rocket"
THREAT_KIND_DRONE = "drone"

PLATFORMS = [Platform.BINARY_SENSOR, Platform.SENSOR]
